### PR TITLE
Remove unnecessary logging. Fix item removal bug

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by kriation** [comment]
Hey Beschio,
Thanks for the pull. Unfortunately, I'm not going to merge it for the following reasons:
1. There are three separate changes in the commit that are not correlated (also, the commit comment only reflects two of the changes)
2. It does not address the issue if a stack of items is in an item slot; in fact, after testing, it looks like your code removes the entire stack instead of one item when 'helmeted'

If you could separate out the changes into three separate commits, we can discuss each change.

**Comment by ghost** [comment]
Hello Kriation,

The original bug was not that it took an entire stack and put it on the player's head. It was that it would remove any other stacks like it ie. same name, amount, damage etc. as illustrated [here](https://gfycat.com/PlayfulNecessaryAmericanredsquirrel). (Notice how it removes all other stacks of 16 stone, yet only puts 16 stone in the helmet slot)

As you can see, the original clears out way too many slots and as a result, items are lost. I feel as though it is up to the player how many items they want on their head. As such they can choose to hold as many items as they'd like in their hand and execute the command. This is also the original intended behaviour.

I do not believe the intent of the update was to ensure only 1 of the items in the stack were helmeted but rather to prevent item loss (CC: @Ekzim)
The changes I've made means that it will _only_ touch the original slot's itemstack and no other stacks like it in the inventory. ([Illustration](https://gfycat.com/HilariousPreciousIndianpangolin))

As for the other commits:
1. Enable/Disable logging is natively handled by bukkit and therefore unnecessary.
2. As for the command name check, [Command#getName()](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/command/Command.html#getName%28%29) returns the name of the command as defined in the plugin.yml ie. without the prepended `/`. As a result, the check would always fail. (This is also how it is in the original, non-github source code)

**Comment by kriation** [comment]
Hello Beschio,

Thank you for breaking up the commits.

Regarding your comments on one item vs. an entire stack for a helmet, I respectively disagree. If we permit a use to 'helmet' any number of items up to a max stack number on their head, it's effectively giving the user one more inventory slot. With that functionality, the mod now becomes a change to gameplay rather than an aesthetic one. My understanding is that the modification was originally designed as an aesthetic one, especially in the case for the use by the ImagineCraft server. 

I'll leave it up to @Ekzim to decide on whether we should permit users to 'helmet' n number of the same item, or simply one item... or provide the ability to do both both based on permission.

**Comment by kriation** [comment]
@Ekzim has spoken!
http://imaginecraft.org/viewtopic.php?f=54&t=2649&p=12716#p12717

The code should remove one item from a held stack (regardless of size), and return it to the inventory when removed from the head.

**Comment by kriation** [comment]
Closing as changes in pull #2 meet the requirements of the plugin.

**Pull request closed without merging**
